name: Build Docker Image

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Nix
              uses: cachix/install-nix-action@v27
              with:
                  extra_nix_config: |
                      extra-substituters = https://devenv.cachix.org
                      extra-trusted-public-keys = devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=

            - name: Build Docker image with Nix
              run: nix build .#docker

            - name: Load Docker image
              run: docker load < result

            - name: Test Docker image
              run: docker run nixtest:latest

            - name: Save Docker image as artifact
              run: |
                  docker save nixtest:latest -o nixtest-docker.tar

            # - name: Upload Docker image artifact
            #   uses: actions/upload-artifact@v4
            #   with:
            #       name: nixtest-docker-image
            #       path: nixtest-docker.tar
            #       retention-days: 7
